=== PonyvilleDeveloper/BIT_DBbackend/docs/quest_declaration.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="quest"> <xs:complexType>
        <xs:sequence>
            <xs:element name="meta">
                <xs:complexType> <xs:sequence>
                    <xs:element name="operator">
                        <xs:complexType> <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="id" type="xs:integer"/>
                            </xs:extension>
                        </xs:simpleContent> </xs:complexType>
                    </xs:element>
                    <xs:element name="inspector" maxOccurs="unbounded" minOccurs="1">
                        <xs:complexType> <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="id" type="xs:integer"/>
                            </xs:extension>
                        </xs:simpleContent> </xs:complexType>
                    </xs:element>
                    <xs:element name="date" type="xs:date"/>
                </xs:sequence> </xs:complexType>
            </xs:element>
            <xs:element name="task" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType> <xs:sequence>
                    <xs:element name="object">
                        <xs:complexType> <xs:sequence>
                            <xs:element name="address" type="xs:string"/>
                            <xs:element name="description" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer"/>
                        <xs:attribute name="type" type="xs:integer"/>
                    </xs:complexType>
                    </xs:element>
                    <xs:element name="target" type="xs:string"/>
                    <xs:element name="result">
                        <xs:complexType> <xs:sequence>
                            <xs:any namespace="##any" processContents="lax" maxOccurs="unbounded" minOccurs="0"></xs:any>
                        </xs:sequence> </xs:complexType>
                    </xs:element>
                    <xs:element name="comment" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:integer"/>
                    <xs:attribute name="type" type="xs:integer"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer"/>
        <xs:attribute name="test"/>
    </xs:complexType> </xs:element>
</xs:schema>

=== PonyvilleDeveloper/BIT_DBbackend/docs/quest_example.xml
<?xml version="1.0" encoding="UTF-8"?>

<quest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./quest_declaration.xsd" id="0" test="">
  <!-- Документ описывающий задание, формируется приложением оператора и хранится на сервере БД -->
	<meta>
	<!-- Тег с метаданными о задании -->
		<operator id="0"><!-- Сюда ФИО оператора, создавшего задание --></operator>
		<inspector id="0"><!-- Сюда ФИО задействованного инспектора --></inspector>
		<date>2024-11-20<!-- Дата создания задания --></date>
	</meta>
  <task id="0" type="0">
    <!-- Отдельная задача внутри задания -->
    <object id="0" type="0">
      <!-- Объект, который нужно проверить -->
      <address><!-- Адрес объекта --></address>
      <description><!-- Описание конкретного объекта --></description>
    </object>
    <target><!-- Цель задачи (что нужно сделать) --></target>
    <result>
      <!-- В этом теге размещается XML-код анкеты -->
    </result>
    <comment><!-- Блок для комментариев оператора --></comment>
  </task>
</quest>
